# .github/workflows/deploy-slides.yml
name: Deploy All Slides

on:
  push:
    branches: [ main ]
    paths:
      - 'slides/**.md'           # NUR wenn .md files in slides/ geändert werden
      - 'slides/images/**'       # Oder wenn Bilder geändert werden
  workflow_dispatch:             # Manueller Trigger möglich

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Marp
        run: npm install -g @marp-team/marp-cli
      
      - name: Build all slides
        run: |
          mkdir -p dist
          
          # Copy images if they exist
          [ -d "slides/images" ] && cp -r slides/images dist/
          
          # Convert every .md to HTML and PDF
          for file in slides/*.md; do
            if [ -f "$file" ]; then
              name=$(basename "$file" .md)
              echo "Building: $name"
              marp "$file" -o "dist/${name}.html" --allow-local-files
              marp "$file" -o "dist/${name}.pdf" --allow-local-files || true
            fi
          done
      
      - name: Generate index
        run: |
          cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>All Presentations</title>
              <style>
                  body { 
                      font-family: system-ui; 
                      max-width: 900px; 
                      margin: 0 auto; 
                      padding: 2rem;
                  }
                  h1 { color: #2ea043; }
                  .slides { 
                      display: grid; 
                      gap: 1rem; 
                      margin-top: 2rem;
                  }
                  .slide-item {
                      display: flex;
                      justify-content: space-between;
                      align-items: center;
                      padding: 1rem;
                      background: #f5f5f5;
                      border-radius: 8px;
                  }
                  .slide-title { 
                      font-weight: 500; 
                      text-transform: capitalize;
                  }
                  .slide-links { 
                      display: flex; 
                      gap: 0.5rem;
                  }
                  a {
                      padding: 0.5rem 1rem;
                      text-decoration: none;
                      border-radius: 4px;
                      color: white;
                  }
                  .btn-view { background: #2ea043; }
                  .btn-pdf { background: #e74c3c; }
              </style>
          </head>
          <body>
              <h1>📚 Course Presentations</h1>
              <div class="slides">
          EOF
          
          # Add all presentations to index
          for file in dist/*.html; do
            if [ -f "$file" ] && [ "$file" != "dist/index.html" ]; then
              name=$(basename "$file" .html)
              title=$(echo "$name" | sed 's/[-_]/ /g')
              
              echo "<div class='slide-item'>" >> dist/index.html
              echo "  <span class='slide-title'>$title</span>" >> dist/index.html
              echo "  <div class='slide-links'>" >> dist/index.html
              echo "    <a href='${name}.html' class='btn-view'>View</a>" >> dist/index.html
              [ -f "dist/${name}.pdf" ] && echo "    <a href='${name}.pdf' class='btn-pdf'>PDF</a>" >> dist/index.html
              echo "  </div>" >> dist/index.html
              echo "</div>" >> dist/index.html
            fi
          done
          
          echo "</div></body></html>" >> dist/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4